apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neptune-mysql-secret
  namespace: neptune
spec:
  encryptedData:
    MYSQL_DATABASE: AgBwLPNKSTiemXYIG3EGiXQvCj5ysX/U9H44/EkDQ0uCXTa7GNbn/+uRvxHKl/1mdAZotqYUBGWrAPpfQ8O41HiYWVTiSCxymKDZ9tLoCHVmjgwy4AzmFZlPnEVMHxk0BpVST7xhL/SjOhOXBvl4rde0XBKm/3FGSYBFJCtvOa9jnP1vEjLhlRfRcO2HHA3tRP72phhbhHrrYOJ1wxAfESm8MTbd3VvLs2i7yT7kkxk/FTB0GzzuSSynhIb0auzhf5Qn/gFhE33S2i5Td9m/BfgOjte+iAmdzfBOvj+a8DLBO/UICWwL7jYaNV9JukgBl4JtEW1NcPqft/leYh5dhJEWrd9f+BjSMSZj54So1+4WfLKvvFGqcq77WFv8626LVhnwZDfF/q0t2P+Bt4Rs/ZCu0abf6yoSLKjt+xSQ8yrE17suii/BVF9G4oS8R5JGj6JJNlGqPHBe40dh0abJd9mdUpjc1RUChJVRmdfNTc6EJ868keXjOrWlhSQC/jmeumPTlHvSPdeiXQcgxJge6BnNTjpwQftPP1ijGQj44HDny5hGpncyDtLE7HC33KqatfiN3u+7MyxnAzgGQEch9pQVLA0hlulYkVBXmhazqObYiUKSgBRVuSXLD1B/at2x0GMfNN8qeAogx99AjXy1eSh6V8Cd9ziXxT3EK9kgOhsN0BSS55qFN87vWpieHXwoi7Fad82xad2J
    MYSQL_PASSWORD: AgCaFpL7R8tE2fRFE8WoAms3nGwnBy2edWuxCMlhfgeQG57MDW4J6OGbVW2LTXX9fKIU/15BjjsT9pZ73z421nrqFHmTG8Lcivcz0xw8QW+n0g726bgf1Qw9KJV4yFIYOa27NZiAqyNBgIh+e8TX7rfKcm29SNiRYCwDtv9l9aw0rYpuDEOs0cX+CDBrjX9XFy9xcvCk6GUMQPVP2InHL4sFjM80LH+dzmunbozf6UzFr4k2pN3aCoDzFBxuon0tKSDpbNMeZVkd/aZo68hA/z1Lw7Dd5J+NtQ7+8b4BQgF7Y2X8aLtXw7H08QlhhMRwgynMn00zMxA8seq4vzAfhyPJagpSUpXAx2kGCjKiYqjgvtvkRaJR/M11r+FFVy6EagomLcm5JYu4xGCqp9xdH0/LIwQz/TpdH2XLRFNRpK00Xo9BqMKQb8vs2fxD34OSaIAXXRVNsLXPBB/Q9eJL7SIFgt+zwJguInRiHMrzW1OT2lqjduf0oIDLR9j7qYazemYVe3UgjxfqpCSQhleCMjUV2aneN9cJULe27FzeY4m1iwkC1nyIkJ7ZxMIaJjrW/AUbXHtOBflZ/e2aeS1hNifTMp67I/5kE4NutSaDb824sdtEmjjGHnUO4kDgKt47Mtv6azt3ph22a416KU8sXPf+sISEDyLGImAr48+C38UKTjkfPg3QZ+FHmK4ciSgmIB2D30RESsNc
    MYSQL_ROOT_PASSWORD: AgBmCBjRJTslsp6diyIpfFgrR9sgy6z0oRyWOKCqPKkkPF7xv6/ICQpw0cIn7attAuzev5wxsjnqne9ZI1aorSzSyHhtA0Uk+xSxQpj27I8dEuEfM0sT5xMmdOlgr4aVbMJDsLrUKO39IRQraVqIDO4QFCQyqcCGzFLiHMKolgNWb4Yfw2mGi/WoZslGeVN7y2tzYQMnaGHLsb+KcMY/nI7TF6+azsmx8zoOAaBGU4qhrijuKaVIfrURALD7UbGPp8wbUUXkSEGQ5EjexI+RevTUaL4SUqXolsMZvqOHStrjFzw/vYfNyiQqxBNt/I+8wL0XrNYD3z5Xu55c0DXMEhRw1DwGiMNJZpGEY/ydl0GFXAnbxQDlk5L1ys8LuYufqQaI+tr7MhhnLO7Q5ThvC9D2cAouEjgmvRqxkgHuIXdngWSD4pdib+9RkBPoCURQl7mFSnnmaxxmONOZ0CfKg0l+RrWHCwgWvrdlzLNgGJcnhznUbBEHOIKsmXJ4e2iLX0PJBnGCPQshPLMJOm5oSy/dxUJFALKrw0UxjOJLgen6smNfSXnc8r/XBM+KQD9WmvA+ANV4EDEZeEiFykQxM1AdGiFWUIfhJXbzPDYXmPGzPwTVNX8nEzDKzmIVVzWUj/TG8mG73cDZPIWm9nCEaPjzux5yI17D2XYZf33dwuHrZ6D7log3b8Yktg6gPQiSfvUD/f/7
    MYSQL_USER: AgA/eKovMcBhlUWVH1UVh28AolGttZchDR//Dvj5fsu6LOC9cLGH2zYaOjyArArETAWvJJr5IXtCuDivdr5/g/tKsKoaT/MiQAkzA6++VrqLAOWcICDQSSJtGtp9IafyjtM20WoNymYQPpS7WisZ/wo5ywl1VQ5S6a0lBDhNmOLdihxu8T4ijZIajtV4CDUf6buIEoAFjTQKHLULTvIBtyCU7qxBL8Kd4BV/Gow+Tu9LJP+vXjK8N33enWGg4HtygTdKTOkdaLrHDXFW06GzN0r9jUtIWChloyvPHycMpKZft/R8bsVCAmaK4Uz/dYdPpvPhxzWYN2hbLLIGDPdvGpxkMIRSDg5zWb90q1c1I8dYi+wkoDIzAuGl/xelgG52A61gKjY0mDROhqkmjVJn6wPC+zxxITAuNIBTaEvyN5uy3kxBD8IQ+To+rGoeNSUPQsfWraTJUj9OhaGaSgZVy5vFvTJ/hAjdDxx0sXaQpL0kFu1q9an5ZS6/8/8jsKeKE5VcKJdqoX/zd+4Ilo4kkoM7MIDxi8Odc+9cv9Zs5BrufOirqsQP7YTx6V576qJgZHXySee8DZEFz+VdEO1HBDInUVEJ/tmAyPwESUhTFwaDRA3k1bTaTeXwvdM5fPydc6eSYanvURulqXrWjzZn6rcYiCpe/gTEMzfdjIsLEZyOC/GMSTFcYfV9qxA3tC77iMk7T+JYXnXr
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/created-by: ssbostan
        app.kubernetes.io/name: mysql
        app.kubernetes.io/part-of: neptune
        app.kubernetes.io/version: "8"
      name: neptune-mysql-secret
      namespace: neptune
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: neptune-neptune-secret
  namespace: neptune
spec:
  encryptedData:
    NEPTUNE_API_DATABASE_URI: AgAhkXZ6dml7o4j/QeE/jkjGbWQ6HsRuw0UMCjhYJKhAXjE4j8oumypy0vg57dQOnF2x6blvmp+h4QH0tO0zo+NPNlAnRRSAOpdiGQlPKQH+08ffbhM2FFFIL54fMIPAUw6KVJxXGDCZ0VERwoABIFKrEMipwd/Fok6qoEsfgs4jTEdPfT93XxEoQfMjuJ4Ws1vu/++1y/VrczxDfQzj2Jdt2Bj7liYL8h3uFJqZntIQRtaIUAu9EWYEyt3EnnFhSsTIE9ZXQRTmkE9kEb8fW6SD8dw8SLTIUHg6mCqbVZli8PUeKJnXaHVvDkhPARtwgb9q8mG9CgIbpv/QaoEBuXXDKhNHufNt6wPSn0AtVKkQG5BbgzISMYuzVinzfscvzBirmlAZG4IitI0O+fULce+afpGU6pT7JfRrQCjnWmdy78w14zIR8JwZeyfijZdD5FSPixNlUSXaRm0ZpqWL6VSbix8g9Kzc6BFoRpm2phQJx5r2VfOX1iuqEQvooySSHbryf78z2eUkEfxUs4fq3Das+05hoNB6KHH7rVUJO8WukURGH0HNDbkzpQy8IKlGMtgZenj4lzZxwqtT02PEYDYXVxizDcscLvUcqasoJzjoRjIeA2/HLcecd9zBlA3pSU1+k4JdEGeEPuO/C6lyagKcypEesjfNIXULTxp9RGvU8s4AMBKSrAjyQiBHsed7DsCRzKWWut6tKCPtO0EEjEOfMKLlsqv2iL/S9LfOZu/IhcN/0geB298G/pNRcaikA76SbahZbMsdq9Yt
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/created-by: ssbostan
        app.kubernetes.io/name: neptune
        app.kubernetes.io/part-of: neptune
        app.kubernetes.io/version: 1.0.0
      name: neptune-neptune-secret
      namespace: neptune
