apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.neptune.service.type }}
  selector:
    {{- include "labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.neptune.service.port }}
      targetPort: 8080
